name: CI for Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Checkstyle
        run: sudo apt-get install checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check -c /google_checks.xml src/main/java/password/AwesomePasswordChecker.java

  unit-tests:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Run Unit Tests
        run: mvn test

  test-coverage:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Run JaCoCo for Coverage
        run: mvn clean test jacoco:report

  performance-tests:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - uses: actions/checkout@v2
      - name: Run Performance Tests
        run: mvn -Dtest=AwesomePasswordCheckerTest test
